name: run interpolator unit tests
on:
  push:
    branches:
      - master
      - paul
  pull_request:
    branches:
      - master
      - paul
jobs:
  build:
    name: running unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: run unittest script
        run:
          python test_example.py
