name: run interpolator unit tests on docker
on: [pull_request]
jobs:
  build:
    name: running unit tests in docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker and use it
        uses: ./action-c
